backend:
  name: github
  repo: abdulrhman-aas/my-store  # استبدل باسم المستخدم واسم المستودع لديك
  branch: main

media_folder: "images/uploads"   # المكان الذي تُرفع فيه الصور
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "الهواتف"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "الوصف", name: "description", widget: "text" }
      - { label: "السعر", name: "price", widget: "number" }
      - { label: "الصورة", name: "image", widget: "image" }
